#!/usr/bin/env node
/* ============================================================================
   FocusDAW — 폰트 로컬 임베딩 (v2.11.0)
   ----------------------------------------------------------------------------
     node tools/fetch-fonts.js

   Google Fonts 에서 앱이 쓰는 폰트를 받아 assets/fonts/ 에 둔다.
     assets/fonts/fonts.css        — 모든 창이 <link> 하나로 읽는 @font-face 모음
     assets/fonts/files/*.woff2    — 실제 폰트 파일

   ── 왜 이렇게 하는가 ───────────────────────────────────────────────────────
   v2.10.x 까지 창 9개가 전부 fonts.googleapis.com 을 CDN 으로 읽었다. 오프라인이면
   조용히 시스템 폰트로 떨어졌다(워터마크·조성 표시·시간 표시의 모양이 바뀐다).

   🔴 Google 이 내려 주는 CSS 를 **그대로** 쓴다 — unicode-range 조각까지 그대로.
   Nanum Myeongjo 는 한글이라 조각이 90개가 넘는데, 브라우저는 화면에 나온 글자가
   든 조각만 읽으므로 파일이 많아도 로딩 비용은 CDN 때와 같다. 우리가 직접
   서브셋하지 않으므로 Nanum 의 예약 폰트 이름(RFN) 문제도 생기지 않는다
   (앱개발.md v2.5.5 기록).

   폰트나 웨이트를 더하려면 아래 FAMILIES 를 고치고 다시 돌린다. 같은 URL 은
   파일 하나로 합친다(가변 폰트는 웨이트마다 같은 파일을 준다).
   ========================================================================== */

const fs = require('fs');
const path = require('path');

// Google Fonts css2 의 family= 값 그대로. 각 창이 쓰던 웨이트의 합집합이다.
const FAMILIES = [
  'Cinzel:wght@400',
  'Orbitron:wght@400',
  'Space+Grotesk:wght@400;500;600;700',
  'Space+Mono:wght@400;700',
  'Michroma',
  'Saira+Condensed:wght@100;200',
  'Elms+Sans',
  'Tai+Heritage+Pro',
  // 워터마크 — 웨이트 400 만. ui-mixer.jsx 의 fontWeight 와 반드시 같이 움직인다(v2.5.6).
  'Google+Sans+Flex:wght@400',
  'Nanum+Myeongjo:wght@400',
];

// woff2 를 받으려면 최신 브라우저 UA 가 필요하다(아니면 ttf 를 준다).
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'assets', 'fonts');
const FILES = path.join(OUT, 'files');

async function get(url, binary) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return binary ? Buffer.from(await res.arrayBuffer()) : res.text();
}

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

(async () => {
  fs.rmSync(FILES, { recursive: true, force: true });
  fs.mkdirSync(FILES, { recursive: true });

  const byUrl = new Map();          // 원격 URL → 로컬 파일 이름
  const counters = new Map();
  let css = '/* Generated by tools/fetch-fonts.js — do not edit by hand. */\n';
  let bytes = 0;

  for (const fam of FAMILIES) {
    const src = await get(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`);
    const out = [];
    for (const m of src.matchAll(/(\/\*[^*]*\*\/\s*)?@font-face\s*\{[^}]*\}/g)) {
      let block = m[0];
      const family = /font-family:\s*'([^']+)'/.exec(block)[1];
      const weight = (/font-weight:\s*(\d+)/.exec(block) || [, '400'])[1];
      const style = (/font-style:\s*(\w+)/.exec(block) || [, 'normal'])[1];
      block = await replaceAsync(block, /url\((https:[^)]+)\)/g, async (_, url) => {
        if (!byUrl.has(url)) {
          const key = `${slug(family)}-${weight}${style === 'italic' ? 'i' : ''}`;
          const n = (counters.get(key) || 0) + 1;
          counters.set(key, n);
          const name = `${key}-${String(n).padStart(3, '0')}.woff2`;
          const buf = await get(url, true);
          fs.writeFileSync(path.join(FILES, name), buf);
          bytes += buf.length;
          byUrl.set(url, name);
        }
        return `url(files/${byUrl.get(url)})`;
      });
      out.push(block);
    }
    if (!out.length) throw new Error(`no @font-face for ${fam}`);
    css += `\n/* ---- ${fam} ---- */\n` + out.join('\n') + '\n';
    console.log(`${fam.padEnd(36)} ${out.length} faces`);
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
  console.log(`\n${byUrl.size} files · ${(bytes / 1024 / 1024).toFixed(2)} MB → ${path.relative(ROOT, OUT)}`);
})().catch((e) => { console.error(e); process.exit(1); });

async function replaceAsync(str, re, fn) {
  const parts = [];
  let last = 0;
  for (const m of str.matchAll(re)) {
    parts.push(str.slice(last, m.index), await fn(...m));
    last = m.index + m[0].length;
  }
  parts.push(str.slice(last));
  return parts.join('');
}
